spring:
  webflux:
    static-path-pattern: /public/**
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /public/**
  resources:
    add-mappings: true
    cache:
      period: 3600
  sbp:
    plugins-root: "demo-webflux/plugins"
    runtime-mode: development
    enabled: true
    classes-directories:
      - "out/production/classes"
      - "out/production/resources"
      - "build/classes/java/main"
      - "build/resources/main"
    controller:
      base-path: sbp
  flyway:
    enabled: false
#  main:
#    allow-bean-definition-overriding: true

springdoc:
  cache:
    disabled: true