language: java
install:
  - ./gradlew :pf4j-spring-boot-support:jar
  - ./gradlew :pf4j-spring-boot-start:jar
  - ./gradlew :demo-plugin-author:copyDependencies
services:
  - postgresql
before_script:
  - psql -c 'create database pf4j;' -U postgres