language: java
jdk:
  - oraclejdk8
install:
  - ./gradlew :pf4j-spring-boot-support:jar
  - ./gradlew :pf4j-spring-boot-starter:jar
  - ./gradlew doMigration
  - ./gradlew buildApp
  - ./gradlew copyDependencies
before_install:
  - psql -c 'create database "pf4j";' -U postgres
  - psql -c 'create database "pf4j-test";' -U postgres
services:
  - postgresql
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
sudo: true