language: java
jdk:
  - oraclejdk8
  - openjdk8
before_install:
  - psql -c 'create database "sbp";' -U postgres
  - psql -c 'create database "sbp-test";' -U postgres
install:
  - ./gradlew :sbp-core:jar
  - ./gradlew :sbp-spring-boot-starter:jar
  - ./gradlew doMigration
  - ./gradlew buildApp
  - ./gradlew copyDependencies
services:
  - postgresql
addons:
  postgresql: "9.6"