name: CI Test

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: hankcp/postgres-test:latest
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install PostgreSQL 11 client
      run: |
        sudo apt update
        sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -yqq install libpq-dev postgresql-client-11
    - run: |
        psql -c 'create database "sbp";' -U postgres
        psql -c 'create database "sbp-test";' -U postgres
      env:
        PGHOST: localhost
        PGUSER: postgres
    - run: ./gradlew clean :sbp-core:jar :sbp-spring-boot-starter:jar -PspringBootVersion=2.2.13.RELEASE
    - run: ./gradlew copyDependencies doMigration buildApp -PspringBootVersion=2.2.13.RELEASE
    - run: ./gradlew check -PspringBootVersion=2.2.13.RELEASE

    - run: ./gradlew clean :sbp-core:jar :sbp-spring-boot-starter:jar -PspringBootVersion=2.3.12.RELEASE
    - run: ./gradlew copyDependencies doMigration buildApp -PspringBootVersion=2.3.12.RELEASE
    - run: ./gradlew check -PspringBootVersion=2.3.12.RELEASE

    - run: ./gradlew clean :sbp-core:jar :sbp-spring-boot-starter:jar -PspringBootVersion=2.4.13
    - run: ./gradlew copyDependencies doMigration buildApp -PspringBootVersion=2.4.13
    - run: ./gradlew check -PspringBootVersion=2.4.13

    - run: ./gradlew clean :sbp-core:jar :sbp-spring-boot-starter:jar -PspringBootVersion=2.5.14
    - run: ./gradlew copyDependencies doMigration buildApp -PspringBootVersion=2.5.14
    - run: ./gradlew check -PspringBootVersion=2.5.14

    - run: ./gradlew clean :sbp-core:jar :sbp-spring-boot-starter:jar -PspringBootVersion=2.6.14
    - run: ./gradlew copyDependencies doMigration buildApp -PspringBootVersion=2.6.14
    - run: ./gradlew check -PspringBootVersion=2.6.14

    - run: ./gradlew clean :sbp-core:jar :sbp-spring-boot-starter:jar -PspringBootVersion=2.7.8
    - run: ./gradlew copyDependencies doMigration buildApp -PspringBootVersion=2.7.8
    - run: ./gradlew check -PspringBootVersion=2.7.8

    - run: ./gradlew publish -Pversion=-SNAPSHOT -P'signing.keyId=${{ secrets.signingKeyId }}' -P'signing.password=${{ secrets.signingPassword }}' -P'sonatypeUsername=${{ secrets.sonatypeUsername }}' -P'sonatypePassword=${{ secrets.sonatypePassword }}'
