name: CI Test

on: [push]

jobs:
  openjdk11:
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: docker ps --all
    - run: ./gradlew :sbp-core:jar
    - run: ./gradlew :sbp-spring-boot-starter:jar
    - run: psql -c 'create database "sbp";' -U postgres
    - run: psql -c 'create database "sbp-test";' -U postgres
    - run: ./gradlew doMigration
    - run: ./gradlew buildApp
    - run: ./gradlew copyDependencies
    - run: ./gradlew check
