name: CI Test

on: [push]

jobs:
  openjdk11:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install PostgreSQL 11 client required for loading structure.sql
      run: |
        sudo apt update
        sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -yqq install libpq-dev postgresql-client-11
    - run: psql -c 'create database "sbp";' -U postgres
      env:
        PGHOST: localhost
        PGUSER: postgres
    - run: psql -c 'create database "sbp-test";' -U postgres
    - run: ./gradlew :sbp-core:jar
      env:
        PGHOST: localhost
        PGUSER: postgres
    - run: ./gradlew :sbp-spring-boot-starter:jar
    - run: ./gradlew doMigration
    - run: ./gradlew buildApp
    - run: ./gradlew copyDependencies
    - run: ./gradlew check
