name: Java CI

on: [push]

jobs:
  openjdk11:
    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:12
#        ports:
#          - 5432:5432
#        volumes:
#          - init-db:/docker-entrypoint-initdb.d
#          - postgresql.conf:/etc/postgresql/postgresql.conf
      services:
        postgres:
          image: postgres:12
          ports:
            - 5432:5432
          volumes:
            - postgresbin:/usr/bin
    steps:
    - uses: actions/checkout@v1
#    - uses: hank-cp/postgresql-action@v1
#      with:
#        postgresql version: '12'
#        postgresql init scripts: 'init-db'
#        postgresql conf file: 'postgresql.conf'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: postgresbin/psql -c 'create database "sbp";' -U postgres
    - run: postgresbin/psql -c 'create database "sbp-test";' -U postgres
    - run: ./gradlew :sbp-core:jar
    - run: ./gradlew :sbp-spring-boot-starter:jar
    - run: ./gradlew doMigration
    - run: ./gradlew buildApp
    - run: ./gradlew copyDependencies
    - run: ./gradlew check install
